import {CHARACTERS,CLASSES} from './data/characters.js';
import {ENEMIES} from './data/enemies.js';
import {CHAPTERS} from './data/chapters.js';
import {MISSIONS} from './data/missions.js';
import {LESSONS} from './data/lessons.js';
import {load,save} from './systems/save.js';
import {buy,addMoney} from './systems/economy.js';
import {Battle} from './engine/battle.js';

let state=load(),battle=null,mission=0,currentChapter=null,sceneIndex=0,lesson=null;
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const cBy=id=>CHARACTERS.find(c=>c.id===id); const eBy=id=>ENEMIES.find(e=>e.id===id);
function nav(id){$$('.page').forEach(x=>x.classList.remove('active'));$('#'+id)?.classList.add('active');scrollTo(0,0)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2600)}
function sync(){state=load();$('#money').textContent=state.money.toLocaleString('pt-BR');renderCharacters();renderShop();renderMission();renderLessons();renderChapters()}
function bar(v,max,cls){return `<div class="${cls}"><i style="width:${Math.max(0,Math.min(100,v/max*100))}%"></i></div>`}
function sprite(c){return `<img class="sprite" src="assets/characters/${c.id}.svg" alt="Sprite representativo de ${c.name}">`}
function card(c,teamView){let owned=state.unlocked.includes(c.id),inTeam=state.team.includes(c.id);return `<article class="card ${owned?'owned':''}">${sprite(c)}<span class="tag">${CLASSES[c.class].name}</span><span class="tag">${c.rarity}★</span><h3>${c.name}</h3><p class="lore">${c.lore}</p><div class="stats"><span>HP ${c.hp}</span><span>ATK ${c.atk}</span><span>DEF ${c.def}</span><span>SPD ${c.spd}</span></div><div><small>${CLASSES[c.class].desc}</small></div>${c.skills.map(s=>`<div class="skill-mini"><b>${s.name}</b><small>${s.desc}${s.cost?' · ⚡ '+s.cost:' · GRÁTIS'}</small></div>`).join('')}${teamView&&owned?`<button data-team="${c.id}">${inTeam?'REMOVER DA EQUIPE':'ADICIONAR À EQUIPE'}</button>`:''}${!owned?`<button data-buy="${c.id}">DESBLOQUEAR · ${c.cost.toLocaleString('pt-BR')} RYO</button>`:''}</article>`}
function renderCharacters(){$('#teamSummary').innerHTML=state.team.map((id,i)=>{const c=cBy(id);return `<div class="team-slot"><span class="tag">SLOT ${i+1}</span><b>${c?.name||'Vazio'}</b><small>${c?CLASSES[c.class].name:'Escolha um personagem'}</small>${c?`<button data-team="${c.id}">REMOVER</button>`:''}</div>`}).join('')+'<div class="team-slot"><b>VAGAS</b><small>'+state.team.length+'/3 ocupadas</small></div>';$(`#charactersGrid`).innerHTML=CHARACTERS.map(c=>card(c,true)).join('')}
function renderShop(){$('#shopGrid').innerHTML=CHARACTERS.map(c=>card(c,false)).join('')}
function renderMission(){const m=MISSIONS[mission];$('#missionBox').innerHTML=`<span class="tag">${m.lang} · ${m.difficulty}</span><h3>${m.title}</h3><div class="question">${m.q}</div><div class="options">${m.o.map((o,i)=>`<button data-answer="${i}">${o}</button>`).join('')}</div><div class="reward">RECOMPENSA: +${m.reward} RYO</div>`}
function renderLessons(){$('#lessonsGrid').innerHTML=LESSONS.map(l=>`<article class="card"><span class="tag">${l.lang}</span><h3>${l.title}</h3><p class="lore">${l.intro}</p><b>${l.sections.length} módulos + laboratório</b><button data-lesson="${l.id}">ABRIR AULA →</button></article>`).join('')}
function renderChapters(){$('#chapters').innerHTML=`<div class="panel" style="padding:22px"><div class="head"><small>STORY MODE // CHAPTERS</small><h3>CAPÍTULOS DA HISTÓRIA</h3></div>${CHAPTERS.map(ch=>`<div class="chapter-card"><span class="tag">${String(ch.id).padStart(2,'0')} · ${ch.location}</span><h3>${ch.title}</h3><p>${ch.scenes[0].body}</p><small>Inimigos: ${ch.enemyTeam.map(id=>eBy(id)?.name).join(' · ')} · Recompensa ${ch.reward} RYO</small><br><button data-chapter="${ch.id}">LER HISTÓRIA →</button></div>`).join('')}</div>`}
function openChapter(id){currentChapter=CHAPTERS.find(x=>x.id===id);sceneIndex=0;$('#chapterModal').classList.remove('hidden');renderScene()}
function renderScene(){const s=currentChapter.scenes[sceneIndex];$('#chapterContent').innerHTML=`<div class="scene-kicker">${s.text}</div><div class="scene-speaker">${s.speaker}</div><div class="scene-body">${s.body}</div><small>SCENA ${sceneIndex+1}/${currentChapter.scenes.length}</small>`;$('#chapterPrev').disabled=sceneIndex===0;$('#chapterNext').textContent=sceneIndex===currentChapter.scenes.length-1?'ENTRAR EM COMBATE →':'PRÓXIMO →'}
function closeModal(id){$('#'+id).classList.add('hidden')}
function startChapter(){closeModal('chapterModal');const team=state.team.map(cBy).filter(Boolean);if(!team.length){toast('Monte uma equipe antes de entrar em combate.');nav('characters');return}const enemies=currentChapter.enemyTeam.map(eBy).filter(Boolean);battle=new Battle(team,enemies,renderBattle);nav('battle')}
function renderBattle(b,msg=''){if(!b)return;$('#turnText').textContent=`RODADA ${b.round} // ${b.phase.toUpperCase()}`;$('#battleLog').textContent=msg||'';$('#team').innerHTML=b.team.map((x,i)=>`<button class="unit ${i===b.active?'active':''} ${x.hpNow<=0?'dead':''} ${b.acted.has(i)?'acted':''}" data-switch="${i}" ${x.hpNow<=0?'disabled':''}><b>${x.name}</b><small>HP ${x.hpNow}/${x.hp} · ⚡ ${x.enNow}/100 ${b.acted.has(i)?'· AÇÃO FEITA':''}</small>${bar(x.hpNow,x.hp,'hpbar')}${bar(x.enNow,100,'energybar')}</button>`).join('');$('#enemies').innerHTML=b.enemies.map((x,i)=>`<button class="enemy-btn" data-target="${i}" ${x.hpNow<=0?'disabled':''}><div class="unit ${b.targets.includes(i)?'target':''} ${x.hpNow<=0?'dead':''}"><img class="enemy-sprite" src="assets/enemies/${x.id}.svg" alt="${x.name}"><b>${x.name}</b><small>HP ${x.hpNow}/${x.hp}</small>${bar(x.hpNow,x.hp,'hpbar')}</div></button>`).join('');const a=b.actor();if(!a)return;$('#activeInfo').innerHTML=`<b>${a.name}</b><span>${CLASSES[a.class].name} — ${CLASSES[a.class].desc}</span><span>HP ${a.hpNow}/${a.hp} · ⚡ ${a.enNow}/100</span><span>${b.acted.has(b.active)?'AÇÃO ENCERRADA':'PRONTO PARA AGIR'}</span>`;$('#skills').innerHTML=a.skills.map((s,i)=>`<button class="skill ${b.pendingSkill===i?'selected-skill':''}" data-skill="${i}" ${b.phase!=='player'||a.enNow<s.cost||b.acted.has(b.active)?'disabled':''}><b>${s.name}</b><small>${s.desc}</small><em>${s.cost?'⚡ '+s.cost:'BÁSICO'}</em></button>`).join('');const confirm=$('#confirmSkill');confirm.hidden=!(b.pendingSkill!=null&&b.phase==='player');if(b.pendingSkill!=null){confirm.textContent=`EXECUTAR ${a.skills[b.pendingSkill].name} · ${b.targets.length} ALVO(S)`}if(b.lastEvent)animateBattle(b.lastEvent)}
function animateBattle(ev){if(!ev||!ev.length)return;const arr=Array.isArray(ev)?ev:[ev];arr.forEach(x=>{let el;if(x.enemyIndex!=null)el=$$('#enemies .unit')[x.enemyIndex];else if(x.teamIndex!=null)el=$$('#team .unit')[x.teamIndex];if(!el)return;el.classList.remove('attack-anim','hit-anim','heal-anim','guard-anim');void el.offsetWidth;el.classList.add(x.type==='attack'?'attack-anim':x.type==='heal'?'heal-anim':x.type==='guard'?'guard-anim':x.type==='enemyAttack'?'hit-anim':'guard-anim');if(x.damage!=null){const f=document.createElement('span');f.className='float-damage';f.textContent='-'+x.damage;el.appendChild(f);setTimeout(()=>f.remove(),900)}})}
function lessonModal(id){lesson=LESSONS.find(x=>x.id===id);$('#lessonModal').classList.remove('hidden');$('#lessonContent').innerHTML=`<span class="tag">${lesson.lang}</span><h2>${lesson.title}</h2><p>${lesson.intro}</p>${lesson.sections.map(s=>`<div class="lesson-section"><h3>${s.title}</h3><p>${s.text}</p><pre class="lesson-code">${escapeHTML(s.code)}</pre></div>`).join('')}<div class="activity"><span class="tag">LABORATÓRIO</span><h3>Missão prática</h3><p>${lesson.activity.prompt}</p><textarea id="codeEditor" spellcheck="false">${lesson.activity.starter}</textarea><div class="lab-row"><button id="runCode">▶ EXECUTAR</button><button id="debugCode" class="ghost">⌁ ANALISAR / CORRIGIR</button><button id="checkCode" class="ghost">✓ CONFERIR ATIVIDADE</button></div><div id="codeOutput" class="output">Saída do laboratório aparecerá aqui.</div><div id="previewWrap"></div></div>`;$('#runCode').onclick=()=>runLab();$('#debugCode').onclick=()=>debugLab();$('#checkCode').onclick=()=>checkLab()}
function escapeHTML(s){return s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function getCode(){return $('#codeEditor').value}
async function runLab(){const out=$('#codeOutput');const code=getCode();out.className='output';out.textContent='Executando...';if(lesson.activity.type==='js'){const logs=[];try{const fn=new Function('console',code);fn({log:(...a)=>logs.push(a.map(String).join(' '))});out.textContent=logs.join('\n')||'Código executado sem console.log().'}catch(e){out.className='output error';out.textContent='ERRO: '+e.message}}
else if(lesson.activity.type==='css'){const wrap=$('#previewWrap');wrap.innerHTML=`<iframe class="preview" sandbox="allow-scripts"></iframe>`;const frame=wrap.querySelector('iframe');frame.srcdoc=`<style>body{font-family:Arial;background:#fff}.quadrado{margin:35px;width:80px;height:80px;background:cyan}</style><div class="quadrado"></div>`;out.textContent='Preview CSS atualizado abaixo.'}
else if(lesson.activity.type==='python'){await runPython(code,out)}
else if(lesson.activity.type==='sql'){out.textContent=simulateSQL(code)}
else {out.textContent=checkCSharp(code)} }
async function runPython(code,out){try{if(!window.__pyodide){out.textContent='Carregando laboratório Python...';await loadScript('https://cdn.jsdelivr.net/pyodide/v0.26.2/full/pyodide.js');window.__pyodide=await window.loadPyodide()}let logs=[];window.__pyodide.setStdout({batched:s=>logs.push(s)});await window.__pyodide.runPythonAsync(code);out.textContent=logs.join('\n')||'Código Python executado.'}catch(e){out.className='output error';out.textContent='ERRO PYTHON: '+String(e)}}
function loadScript(src){return new Promise((res,rej)=>{const s=document.createElement('script');s.src=src;s.onload=res;s.onerror=()=>rej(new Error('Não foi possível carregar o interpretador Python.'));document.head.appendChild(s)})}
function simulateSQL(code){const q=code.trim().replace(/\s+/g,' ').toUpperCase();if(!q.startsWith('SELECT'))return 'ERRO SQL: este laboratório espera uma consulta SELECT.';if(!q.includes('FROM'))return 'ERRO SQL: faltou FROM.';return 'Consulta válida.\n\nResultado simulado:\nJavaScript | 12\nPython | 10\nCSS | 9\nC# | 8\n\nDica: acrescente WHERE nivel >= 10 para filtrar.'}
function checkCSharp(code){if(!/int\s+hp\s*=\s*100\s*;/.test(code))return 'ANÁLISE: procure uma declaração como “int hp = 100;”.';return '✓ Sintaxe básica da atividade encontrada. Em um projeto real, compile com o .NET SDK.'}
function debugLab(){const out=$('#codeOutput');const code=getCode();if(lesson.activity.type==='js'){try{new Function(code);out.className='output success';out.textContent='✓ Não encontrei erro de sintaxe no JavaScript. Agora execute para conferir o comportamento.'}catch(e){out.className='output error';out.textContent='ERRO DE SINTAXE: '+e.message+'\n\nDica: confira parênteses, chaves, aspas e ponto e vírgula perto do trecho indicado pelo navegador.'}}else if(lesson.activity.type==='python'){out.className='output';out.textContent=code.includes('print(')?'✓ Há um print() no código. Execute para verificar.':'DICA: a atividade precisa usar print(resultado).'}else if(lesson.activity.type==='css'){out.className='output';out.textContent=code.includes('width: 120px')&&code.toLowerCase().includes('background: red')?'✓ As duas regras principais foram encontradas.':'DICA: procure width: 120px e background: red.'}else if(lesson.activity.type==='sql'){out.className='output';out.textContent=simulateSQL(code)}else{out.className='output';out.textContent=checkCSharp(code)}}
function checkLab(){const code=getCode().replace(/\s+/g,' ').trim().toLowerCase();const answer=lesson.activity.answer.replace(/\s+/g,' ').trim().toLowerCase();const ok=lesson.activity.type==='css'?(code.includes('width: 120px')&&code.includes('background: red')):lesson.activity.type==='sql'?code.startsWith('select')&&code.includes('from'):code.includes(answer.replace(/;$/,''));const out=$('#codeOutput');out.className='output '+(ok?'success':'error');out.textContent=ok?'✓ ATIVIDADE CONCLUÍDA! Você entendeu o objetivo.':'Ainda não. Leia a dica, compare com o exemplo e tente novamente.'}

document.addEventListener('click',e=>{
 const navBtn=e.target.closest('[data-nav]');if(navBtn){nav(navBtn.dataset.nav);return}
 const buyBtn=e.target.closest('[data-buy]');if(buyBtn){const c=cBy(buyBtn.dataset.buy),r=buy(c.id,c.cost);toast(r[1]);sync();return}
 const teamBtn=e.target.closest('[data-team]');if(teamBtn){const id=teamBtn.dataset.team,s=load();if(s.team.includes(id))s.team=s.team.filter(x=>x!==id);else if(s.team.length<3)s.team.push(id);else{toast('Equipe cheia. Remova alguém antes.');return}save(s);sync();return}
 const ans=e.target.closest('[data-answer]');if(ans){const m=MISSIONS[mission];if(+ans.dataset.answer===m.a){addMoney(m.reward);mission=(mission+1)%MISSIONS.length;toast(`Resposta correta! +${m.reward} Ryo.`)}else toast('Resposta incorreta. Revise a Academia Zero.');sync();return}
 const les=e.target.closest('[data-lesson]');if(les){lessonModal(les.dataset.lesson);return}
 const chapter=e.target.closest('[data-chapter]');if(chapter){openChapter(+chapter.dataset.chapter);return}
 const close=e.target.closest('[data-close]');if(close){closeModal(close.dataset.close);return}
 if(e.target.id==='chapterPrev'&&sceneIndex>0){sceneIndex--;renderScene();return}
 if(e.target.id==='chapterNext'){if(sceneIndex<currentChapter.scenes.length-1){sceneIndex++;renderScene()}else startChapter();return}
 const sw=e.target.closest('[data-switch]');if(sw&&battle){battle.switch(+sw.dataset.switch);renderBattle(battle);return}
 const tg=e.target.closest('[data-target]');if(tg&&battle){const i=+tg.dataset.target;const skillIndex=battle.pendingSkill??battle.selectedSkill??0;const activeSkill=battle.actor()?.skills[skillIndex];if(activeSkill?.targetMode==='single')battle.setSingleTarget(i);else battle.targetEnemy(i);renderBattle(battle);return}
 const sk=e.target.closest('[data-skill]');if(sk&&battle){const idx=+sk.dataset.skill;const s=battle.actor().skills[idx];battle.selectedSkill=idx;if(s.targetMode==='multi'){battle.pendingSkill=idx;battle.targets=battle.targets.filter(i=>battle.enemies[i]?.hpNow>0).slice(0,s.maxTargets||2);toast(`Selecione até ${s.maxTargets||2} alvos e clique em EXECUTAR SKILL.`);renderBattle(battle);return}if(s.targetMode==='single')battle.setSingleTarget(battle.target);battle.use(idx);return}
 if(e.target.id==='confirmSkill'&&battle&&battle.pendingSkill!=null){const idx=battle.pendingSkill;battle.pendingSkill=null;battle.use(idx);return}if(e.target.id==='defend'&&battle){battle.pendingSkill=null;battle.defend();return}
 if(e.target.id==='basic'&&battle){battle.pendingSkill=null;battle.use(0);return}
});
sync();nav('home');
